[project]
name = "community-grant-dao"
description = "Community Grant DAO on Stacks"
authors = ["tony"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.community-grant-dao]
path = "contracts/community-grant-dao.clar"
clarity_version = 2
epoch = "latest"

[contracts.mock-sip010]
path = "contracts/mock-sip010.clar"
clarity_version = 2
epoch = "latest"
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
